textileio/js-threads

package-lock.json, package.json, packages/core/src/index.ts, packages/core/src/models/index.ts, packages/core/src/thread/info.ts, packages/service/README.md, packages/service/package-lock.json, packages/service/package.json, packages/service/src/index.ts, packages/service/src/options.ts, packages/service/src/store/addrbook.spec.ts, packages/service/src/store/addrbook.ts, packages/service/src/store/headbook.spec.ts, packages/service/src/store/headbook.ts, packages/service/src/store/index.ts, packages/service/src/store/keybook.spec.ts, packages/service/src/store/keybook.ts, packages/service/src/store/metadatabook.spec.ts, packages/service/src/store/metadatabook.ts, packages/service/src/store/threadstore.ts, packages/service/tsconfig.json
This should be merged after its parent branch. Required: github.com/textileio/js-datastore-ttl.
=> [wip] Initial Threads Service store components

package-lock.json, package.json
So that sub-module docs actually get published properly.
=> Adds nojekyll file to docs output

.eslintignore, .gitignore, README.md, package.json, packages/core/package-lock.json, packages/core/package.json, packages/core/src/multiaddr/index.ts, packages/core/src/thread/log.ts, packages/encoding/package.json, packages/encoding/src/index.spec.ts, packages/encoding/src/record.ts, packages/examples/README.md, packages/examples/package-lock.json, packages/examples/package.json, packages/examples/src/chat/index.ts, packages/examples/tsconfig.json, packages/service-client/package.json, packages/service-client/src/index.spec.ts, packages/service/package.json, packages/service/src/index.ts, packages/service/src/service.spec.ts, packages/service/src/service.ts, packages/service/src/store/index.ts
This adds a chat example that is fully compatible with the go-threads chat example. It provides e2e encrypted chat, using a remote threads daemon for the service layer APIs. This should provide a useful example for external devs exploring the lower-level threads APIs.
Fixes #20 
For all relevant packages, tests have been run and updated as needed. They run locally using the same setup as our default CI. No tests were added to the example sub-package, as this _is_ essentially the test.
=> Chat example + various edge case fixes and API improvements

.github/workflows/docs.yml, .github/workflows/test.yml, examples/chat/package.json, package.json, packages/core/package-lock.json, packages/core/package.json, packages/encoding/package.json, packages/service-client/package.json, packages/service/package.json, tsconfig.json
This enables incremental builds for development. It provides _significant_ speedups with local development builds, with minimal additional overhead (some manual package linking). It is based on this excellent blog post: https://betterstack.dev/blog/lerna-typescript-monorepo/
All existing tests run locally. No new _library_ functionality added. This is a pure development 'upgrade'.
- [-] I have made corresponding changes to the documentation
- [-] I have added tests that prove my fix is effective or that my feature works
=> Enables incremental builds

CODEOWNERS
Deletes CODEOWNERS to avoid automatically requesting reviews from all code owners, instead opting for explicit review requests.
Does not affect code tests. Code owners will no longer be automatically requested on all PRs.
- [-] I have added tests that prove my fix is effective or that my feature works
=> Delete codeowners file

packages/core/src/thread/id.ts, packages/database/src/collection.ts, packages/database/src/db.spec.ts, packages/database/src/db.ts
These are various minor fixes and updates that were encountered during a previous PR review.
Fixes #36
Fixes #37 
Fixes #38 
Fixes #46
All existing tests and linter checks pass.
=> Minor nits to address db issues

README.md, package.json, packages/core/README.md, packages/core/package.json, packages/database/README.md, packages/encoding/README.md, packages/encoding/src/coding.ts, packages/encoding/src/event.ts, packages/encoding/src/record.ts, packages/network-client/README.md, packages/network-client/package.json, packages/network-client/src/config.ts, packages/network-client/src/index.ts, packages/network/README.md, packages/network/package.json, packages/network/src/network.ts, packages/network/src/store/index.ts, packages/network/src/store/keybook.ts, packages/store/README.md, packages/store/package.json, packages/store/src/codec.ts, packages/store/src/datastores/domain.ts, packages/store/src/datastores/encoding.ts, packages/store/src/dispatcher.ts, packages/store/src/stores/basic.ts, packages/store/src/stores/jsonpatch.ts, packages/store/src/stores/store.ts
First attempt to pull in docs and start to build out examples etc for js-threads.
Fixes #47.
=> Initial docs push

.github/workflows/test.yml, package.json, packages/core/package-lock.json, packages/core/src/identity.ts, packages/core/src/index.ts, packages/core/src/network/network.ts, packages/core/src/thread/thread.ts, packages/database/package-lock.json, packages/database/src/db.ts, packages/encoding/package-lock.json, packages/encoding/src/record.ts, packages/multiaddr/package-lock.json, packages/network-client/package-lock.json, packages/network-client/src/index.spec.ts, packages/network-client/src/index.ts, packages/network/package-lock.json, packages/network/package.json, packages/network/src/network.spec.ts, packages/network/src/network.ts, packages/store/package-lock.json
Updates to latest go-threads releases. Also includes new Identity setup to be used by js-threads-client.
=> Update to go-threads latest + better Identity generics

README.md
=> Mention websocket requirement in docs

package-lock.json, package.json, packages/core/package-lock.json, packages/core/src/thread/thread.ts, packages/database/package-lock.json, packages/database/src/db.spec.ts, packages/database/src/db.ts, packages/encoding/package-lock.json, packages/network-client/package-lock.json, packages/network-client/src/index.ts, packages/network/package-lock.json
This provides better handling of db info, including the correct thread addresses and keys. Part of ongoing work to improve easy of getting started.
Fixes #151
All existing tests continue to pass, and a new test was added.
=> Better handling of db info

packages/database/src/collection.ts
Simple fix, assuming tests pass... this should just be merged.
=> Hack to try to fix object behavior

packages/client/src/index.ts
=> Export transaction interfaces from index

packages/database/src/db.ts
=> Explicitly define return type for loginfo

packages/database/src/collection.ts, packages/database/src/db.spec.ts, packages/database/src/db.ts
Fixes #191 
Fixes #192
Includes some additional nits, and tests. I went back and forth on various approaches for this, but this felt like the least over-engineering/keeping the fix simple. So went with that.
=> Better error on id mismatch

package.json, packages/client/package-lock.json, packages/context/package-lock.json, packages/core/package-lock.json, packages/core/package.json, packages/database/package-lock.json, packages/encoding/package-lock.json, packages/id/package-lock.json, packages/id/package.json, packages/multiaddr/package-lock.json, packages/multiaddr/package.json, packages/network-client/package-lock.json, packages/network/package-lock.json, webpack.test.js
For some reason, dependabot modifies our package-lock.json files into a state _not_ produced by lerna? Further investigations are required.
=> Dep updates and small nits

packages/client/package-lock.json, packages/client/package.json, packages/client/src/index.ts, packages/client/src/models/ReadTransaction.ts, packages/client/src/models/WriteTransaction.ts, packages/database/package-lock.json, packages/network-client/package-lock.json, packages/network-client/package.json, packages/network-client/src/index.ts
Update to reflect downstream changes to naming conventions.
=> Update to new grpc lib names

packages/client/src/index.spec.ts, packages/client/src/index.ts, packages/client/src/models/ReadTransaction.ts, packages/client/src/models/WriteTransaction.ts, packages/context/src/index.spec.ts, packages/context/src/index.ts, packages/database/src/db.spec.ts, packages/network-client/src/index.spec.ts, packages/network-client/src/index.ts, packages/network/src/index.ts, packages/network/src/network.spec.ts
Renames the Context interface to ContextInterface, and the Provider class to Context
All existing tests pass locally and have been updated to reflect the name changes,
=> feat: context -> contextinterface + provider -> context

packages/context/package.json, packages/context/src/index.spec.ts
Signed-off-by: andrew <andrew@textile.io>
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
=> feat(tests): adds context tests to avoid regressions

README.md, packages/core/package-lock.json, packages/database/package-lock.json, packages/database/src/db.spec.ts, packages/database/src/db.ts, packages/database/src/eventbus.ts, packages/database/src/utils.ts, packages/encoding/package-lock.json, packages/network-client/package-lock.json, packages/network/package-lock.json, packages/network/src/network.ts
Here are a set of changes to the DX flow of using Database, as 'discovered' by working through examples and highlighting pain points. The following issues reflect the fixes and updates that this PR addresses.
Fixes...
All existing tests should continue to pass, and any new APIs/methods have corresponding tests added.
=> Various updates/nits based on DX improvements

packages/client/src/index.ts
fixes https://github.com/textileio/js-threads/issues/346
=> feat(open): adds client.open method

packages/core/src/identity.spec.ts, packages/crypto/src/ed25519.ts
fixes https://github.com/textileio/js-threads/issues/372
=> fix(tests): testing to see if sigs verify

packages/client/src/index.spec.ts, packages/client/src/index.ts, packages/client/src/models/query.ts
When using the Client listener API, the callback now received an annotated object which contains additional information about the update event:
```
export enum Action {
CREATE = 0,
SAVE,
DELETE,
}
export interface Update<T = any> extends Instance<T> {
collectionName: string
instanceID: string
action: Action
}
```
where Instance is now (note the undefined/optional):
```
export interface Instance<T> {
instance: T | undefined
}
```
All tests pass locally, expected to pass remotely. Some tests have been updated to reflect the new interfaces.
=> Listener fix

packages/threads/package.json, packages/threads/src/index.ts
BREAKING CHANGE: this removes Database exports from @textile/threads
=> Don't import/export database

packages/client/src/index.ts
fixes https://github.com/textileio/js-threads/issues/498
=> feat(docs): adds example docs for client apis

packages/client/src/index.spec.ts, packages/client/src/index.ts
This exposes the GetCollectionInfo API on the gRPC layer.
Fixes #505 
Tests have been added for the new API, and existing tests continue to pass locally.
=> Expose getCollectionInfo API

packages/client/package-lock.json, packages/client/package.json, packages/client/src/index.spec.ts, packages/client/src/index.ts, packages/client/src/models/ReadTransaction.ts, packages/client/src/models/WriteTransaction.ts
This is a quick update to get threads-client up to date with go-threads. It also includes some minor fixes and updates unrelated to this. Note that there are breaking API changes with this release, so a major version bump is required. Note also this brings us up to date with Hub and go-threads master, but not the latest release of go-threads, so this should be a pre-release update.
All new and existing tests pass.
=> Updates to latest go threads protos + apis

packages/client/src/index.spec.ts, packages/client/src/index.ts, packages/client/src/models/ReadTransaction.ts, packages/client/src/models/WriteTransaction.ts, packages/multiaddr/package.json, packages/multiaddr/src/codec.ts, packages/multiaddr/src/convert.ts, packages/multiaddr/src/index.ts
This was a missing api from the JS client lib. This PR also includes fixes for other issues, including a more careful dependence on Buffer.
Fixes #534 
Fixes #570 
Tests should all pass, plus several new test cases have been added to check for regressions for during user debugging sessions.
=> Adds verify to write txn

README.md
Adds a disclaimer about alpha/beta software. Also includes a few other docs nits borrowed from go-threads.
Fixes #558 
=> Update readme with disclamer fixes #558

packages/client/src/index.spec.ts, packages/client/src/models/WriteTransaction.ts
=> Return correct response type. 

README.md, lerna.json, package.json, packages/client/package-lock.json, packages/client/package.json, packages/client/src/index.ts, packages/context/src/index.ts, packages/multiaddr/package-lock.json, packages/multiaddr/package.json, packages/security/package-lock.json, packages/security/package.json, packages/security/src/index.ts
This includes various fixes that should make it in before our next Threads release.
Fixes #636
Fixes #621 
Fixes #374 (partly, see also https://github.com/textileio/js-textile/pull/786)
Fixes #637 (partly, was mostly already done)
=> Various nits and fixes before next publish release
